### PR TITLE
Fix package caching and add phpstan to CI

### PR DESCRIPTION
**Pull request by szepeviktor**
Implement #5

### CODE REVIEW

**Comment by olivervogel** [comment]
Any idea to fix the errors?

**Comment by szepeviktor** [comment]
How should we include the `config_path` function?
https://github.com/laravel/framework/blob/0b12ef19623c40e22eff91a4b48cb13b3b415b25/src/Illuminate/Foundation/helpers.php#L287-L290

BTW Why do we use it? It is a part of the framework.

**Comment by olivervogel** [comment]
It is only used in the [ServiceProvider](https://github.com/Intervention/httpauth/blob/master/src/Laravel/HttpAuthServiceProvider.php#L25), which is just relevant, if you are using this package with the Laravel Framework.

I know this is not ideal, if it comes to testing. A better approach would be to create another bridge package exclusively for a framework.

**Comment by szepeviktor** [comment]
Done 🍏 

Not the nicest thing but livable.

**Comment by szepeviktor** [comment]
@olivervogel Mergy-mergy :)

**Comment by szepeviktor** [comment]
Thank you.

**Pull request merged**
