### PR TITLE
Support Laravel 6

### PR DESCRIPTION
**Pull request by jasonvarga**
The service provider for Laravel 6 works the same way as 5.

### CODE REVIEW

**Comment by olivervogel** [comment]
Thank you, I solved this with inheritance in 3d67894b28b9ff3887fb9e4474c6b81ca5614543

**Comment by jasonvarga** [comment]
I thought about that at first but you will have to keep adding files for Laravel 7+. No problem, thanks for sorting it out!

**Comment by jasonvarga** [comment]
Is it possible to get a release?

**Comment by olivervogel** [comment]
https://github.com/Intervention/httpauth/releases/tag/2.1.0

**Pull request closed without merging**
